"""Add lowest_price fields to games table

Revision ID: 70319983c448
Revises: 032df4160b51
Create Date: 2025-12-10 16:50:48.683893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70319983c448'
down_revision = '032df4160b51'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('lowest_price', sa.Float(), nullable=True))
    op.add_column('games', sa.Column('lowest_price_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'lowest_price_date')
    op.drop_column('games', 'lowest_price')
    # ### end Alembic commands ###
